<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6HLJdAh' shared service.

return $this->privates['.service_locator.6HLJdAh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pf' => ['privates', '.errored..service_locator.6HLJdAh.FOS\\RestBundle\\Request\\ParamFetcher', NULL, 'Cannot autowire service ".service_locator.6HLJdAh": it references class "FOS\\RestBundle\\Request\\ParamFetcher" but no such service exists. Try changing the type-hint to "FOS\\RestBundle\\Request\\ParamFetcherInterface" instead.'],
    'user' => ['privates', '.errored..service_locator.6HLJdAh.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.6HLJdAh": it references class "App\\Entity\\User" but no such service exists.'],
]);
