<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.f2lwp6H' shared service.

return $this->privates['.service_locator.f2lwp6H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'role' => ['privates', '.errored..service_locator.f2lwp6H.App\\Entity\\RolesDelSistema', NULL, 'Cannot autowire service ".service_locator.f2lwp6H": it references class "App\\Entity\\RolesDelSistema" but no such service exists.'],
]);
