<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.22V1Cm2' shared service.

return $this->privates['.service_locator.22V1Cm2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'paciente' => ['privates', '.errored..service_locator.22V1Cm2.App\\Entity\\Paciente', NULL, 'Cannot autowire service ".service_locator.22V1Cm2": it references class "App\\Entity\\Paciente" but no such service exists.'],
]);
