<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiController::registerAction' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\ApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ApiController::testRoute' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\ConfiguracionController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ConsultaController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PacienteController::delete' => ['privates', '.service_locator.22V1Cm2', 'get_ServiceLocator_22V1Cm2Service.php', true],
    'App\\Controller\\PacienteController::edit' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\PacienteController::new' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\PacienteController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\RolesDelSistemaController::edit' => ['privates', '.service_locator.f2lwp6H', 'get_ServiceLocator_F2lwp6HService.php', true],
    'App\\Controller\\RolesDelSistemaController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.6HLJdAh', 'get_ServiceLocator_6HLJdAhService.php', true],
    'App\\Controller\\UserController::editState' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::new' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\UserController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ApiController:registerAction' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\ApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ApiController:testRoute' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\ConfiguracionController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ConsultaController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PacienteController:delete' => ['privates', '.service_locator.22V1Cm2', 'get_ServiceLocator_22V1Cm2Service.php', true],
    'App\\Controller\\PacienteController:edit' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\PacienteController:new' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\PacienteController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\RolesDelSistemaController:edit' => ['privates', '.service_locator.f2lwp6H', 'get_ServiceLocator_F2lwp6HService.php', true],
    'App\\Controller\\RolesDelSistemaController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.6HLJdAh', 'get_ServiceLocator_6HLJdAhService.php', true],
    'App\\Controller\\UserController:editState' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:new' => ['privates', '.service_locator.9P48g_d', 'get_ServiceLocator_9P48gDService.php', true],
    'App\\Controller\\UserController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
