nelmio_api_doc:
    documentation:
        info:
            title: Proyecto de soft. Hospital
            description: Aplicacion del grupo 23
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!api/doc) # Accepts routes under /api except /api/doc
